theme: jekyll-theme-slate

title: Jeedom by KiboOst
description: Documentations Jeedom

author:
  name: KiboOst

languages: ["en", "fr"]
defaultLang: fr
languageNames:
  fr: Fran√ßais
  en: English

plugins:
  - jemoji
  - jekyll-seo-tag

markdown: CommonMarkGhPages